language: c
dist: xenial

matrix:
  include:
  - os: linux
    env: DEPLOY_FILE=cutter-deps-linux.tar.gz
  - os: osx
    env: DEPLOY_FILE=cutter-deps-linux.tar.gz

addons:
  homebrew:
    packages:
    - llvm

install: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/llvm/bin:$PATH; fi

script: make

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Yu8nZtKSx2IyehUI66n7JScpGPU58X+sLMCcxfpeoPRSeVJ4DIAgPfAT8ntauVS8sv4dPgIgLtGnoh6HYDNj1e9fSDdfIL0gzDvqAWEbJjLISSnnXZYlmkpAGBbQ6zNMxbBrxg67t2Q1J5LaQ2RTpj2c6vyg51u1Tg7ZRZMYj3ETyks03XrmN3J6alO15p6j174xig7G4eP4cyeBat7hnq56TTIz7+wABCUyxpMVHT4WBy8PCiVStzZ0x2VZOIpcLEQw5s7taGbmwe0XHGIDD+dLVoV6ZJEq3tWuJHxAIj3koMNdBPvwG1yszJE6BkzTyHugjTnfduyBS7EJOCngPFKtCwHWd6YWsbN6aDVI0TpqhU1faZzkOI4hvt46YuPPliy1veUJqzjdE1uVb330GZ7sW7CbDshGHk2ePimPwH338orx7FfqQhyAXJRM9/GX3puogUmrDZD2cNT8a1mK8cRkbDVC275Fw+JL/d2/SwNoqUOJavfvBgeIc9hkHY2MGvBczvnMqX8VyGRI+IlL8PSdzTzaMyPq++P5wDMDbu1D8UuT3l6oTAmHEodgQGpIF/KfPRtWCGVNQ8eD2CZkdN3UdqL0Ztk0vwivshmeB7ETAgSE5OikZleg6ot+qjvNmS5j5QTSEGchbAqehZAsMT+ZliZT4X0MCOfrhrU+IqU=
  file: cutter-deps.tar.gz
  on:
    tags: true
    repo: radareorg/cutter-deps
